name: Build bully-rs for MT7621

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Instalace Cross
        run: cargo install cross --git https://github.com/cross-rs/cross

      - name: Konfigurace Cross pro MT7621 (MIPS + libpcap)
        run: |
          cat << 'EOF' > Cross.toml
          [target.mips-unknown-linux-musl]
          image = "ghcr.io/cross-rs/mips-unknown-linux-musl:edge"
          pre-build = ["dpkg --add-architecture mips && apt-get update && apt-get install -y libpcap-dev:mips"]
          EOF

      - name: Kompilace pro MT7621
        run: cross build --target mips-unknown-linux-musl --release

      - name: Uložení binárky
        uses: actions/upload-artifact@v4
        with:
          name: bully-rs-mt7621
          path: target/mips-unknown-linux-musl/release/bully-rs
